### PR TITLE
Code changes for smart_properties v1.15.0

### PR DESCRIPTION
**Pull request by EiNSTeiN-**
* Update `property` syntax to work with https://github.com/t6d/smart_properties/pull/70.
* Update development dependencies in Gemfile.lock

### CODE REVIEW

**Comment by aried3r** [comment]
Hey! Did this – somewhat silently – remove support for Ruby 2.3?

**Comment by EiNSTeiN-** [comment]
the change in t6d/smart_properties#70 may `dup` a nil object and that is not supported in ruby 2.3

**Comment by AlexWayfer** [comment]
> remove support for Ruby 2.3?

Support of Ruby 2.3 has ended, even security maintenance: https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/

**Comment by aried3r** [comment]
> that is not supported in ruby 2.3

I see. The reason why I'm asking is because the `.gemspec` file still mentions 2.3, so does `.rubocop.yml` and the README.

https://github.com/Shopify/erb-lint/blob/f0d65d75d0d93e7cc1632421e55159847e0f60a3/erb_lint.gemspec#L21
https://github.com/Shopify/erb-lint/blob/f0d65d75d0d93e7cc1632421e55159847e0f60a3/.rubocop.yml#L5
https://github.com/Shopify/erb-lint/blob/f0d65d75d0d93e7cc1632421e55159847e0f60a3/README.md#requirements

> Support of Ruby 2.3 has ended

I realize that, however that sometimes doesn't directly correlate with what gems generally support, though. :)

**Comment by AlexWayfer** [comment]
> I realize that, however that sometimes doesn't directly correlate with what gems generally support, though. :)

I mean, it's better and safer to update dependencies, including Ruby, for supported projects. Or don't update them at all.

> I see. The reason why I'm asking is because the .gemspec file still mentions 2.3, so does .rubocop.yml and the README.

This is bad, yeah.

**Comment by EiNSTeiN-** [comment]
I'll address this in https://github.com/Shopify/erb-lint/pull/134

**Pull request merged**
