### PR TITLE
Add --format option

### PR DESCRIPTION
**Pull request by andersonkrs**
Hey guys! 
At my work, we adopted this gem and we are trying to integrate it with this guy: https://github.com/reviewdog/reviewdog in our CI. But, it has been really hard to do, because this tool uses [vim's errorformat](https://vim-jp.org/vimdoc-en/quickfix.html#error-file-format) and it's not that easy to parse the actual output.

I've seen that there are two proposals to tackle this problem: https://github.com/Shopify/erb-lint/pull/84 https://github.com/Shopify/erb-lint/pull/116, and it hasn't been any movement, so I decided to do this starting point.
This implementation that I've made is strongly inspired by these PRs.

I've added a `--format` option, with that, users can pass the desired output format. To add a new format is straightforward, you just need to create a new inherited class from `Reporter` and implement the method `show` and it will be available on cli automatically. 

So, I've refactored and extracted all the code responsible for reporting results in 2 new classes:
1 - `MultilineReporter` - The default report format
2 - `CompactReporter` - Oneliner report, outputs data using format: `file:line:column: message`. This guy will be really useful for many kinds of integrations like CI, editors, etc. 😃 

This opens the way to include new output formats more easily, like JSON, XML, etc.

### CODE REVIEW

**Comment by fidalgo** [comment]
I'm looking into this to configure [ale](https://github.com/dense-analysis/ale) and CI to have a consistent style across all projects.

**Comment by rafaelfranca** [comment]
Looks good. Can you document this new option in the README?

**Comment by AndersonSKM** [comment]
@rafaelfranca Done.

I did one more little thing, I've extracted the responsibility of show preview messages like `Linting x files ...` into reporter object, because other formats like JSON, XML, etc, can't have that on output.

**Comment by ni3t** [comment]
Hello, 

Is there any progress on merging this change? We are migrating our CI to github actions, and the ability to write a custom reporter would make annotating errors in the changed files view a lot easier. No rush if this is still a WIP.

**Review by devdreamsolution — APPROVED** [review]

**Comment by brendo** [comment]
With the newly released 0.0.36, this PR seems to introduce an error:

```
$ bundle exec erblint --lint-all
NoMethodError: undefined method `delegate' for ERBLint::Reporter:Class
Did you mean?  DelegateClass
  /tmp/bundle/ruby/2.6.0/gems/erb_lint-0.0.36/lib/erb_lint/reporter.rb:36:in `<class:Reporter>'
  /tmp/bundle/ruby/2.6.0/gems/erb_lint-0.0.36/lib/erb_lint/reporter.rb:5:in `<module:ERBLint>'
  /tmp/bundle/ruby/2.6.0/gems/erb_lint-0.0.36/lib/erb_lint/reporter.rb:4:in `<top (required)>'
  /tmp/bundle/ruby/2.6.0/gems/erb_lint-0.0.36/lib/erb_lint.rb:16:in `require'
  /tmp/bundle/ruby/2.6.0/gems/erb_lint-0.0.36/lib/erb_lint.rb:16:in `<top (required)>'
  /tmp/bundle/ruby/2.6.0/gems/erb_lint-0.0.36/lib/erb_lint/cli.rb:3:in `require'
  /tmp/bundle/ruby/2.6.0/gems/erb_lint-0.0.36/lib/erb_lint/cli.rb:3:in `<top (required)>'
  /tmp/bundle/ruby/2.6.0/gems/erb_lint-0.0.36/exe/erblint:6:in `require'
  /tmp/bundle/ruby/2.6.0/gems/erb_lint-0.0.36/exe/erblint:6:in `<top (required)>'
  /tmp/bundle/ruby/2.6.0/bin/erblint:23:in `load'
  /tmp/bundle/ruby/2.6.0/bin/erblint:23:in `<top (required)>'
```

**Comment by andersonkrs** [comment]
> With the newly released 0.0.36, this PR seems to introduce an error:
> 
> ```
> $ bundle exec erblint --lint-all
> NoMethodError: undefined method `delegate' for ERBLint::Reporter:Class
> Did you mean?  DelegateClass
>   /tmp/bundle/ruby/2.6.0/gems/erb_lint-0.0.36/lib/erb_lint/reporter.rb:36:in `<class:Reporter>'
>   /tmp/bundle/ruby/2.6.0/gems/erb_lint-0.0.36/lib/erb_lint/reporter.rb:5:in `<module:ERBLint>'
>   /tmp/bundle/ruby/2.6.0/gems/erb_lint-0.0.36/lib/erb_lint/reporter.rb:4:in `<top (required)>'
>   /tmp/bundle/ruby/2.6.0/gems/erb_lint-0.0.36/lib/erb_lint.rb:16:in `require'
>   /tmp/bundle/ruby/2.6.0/gems/erb_lint-0.0.36/lib/erb_lint.rb:16:in `<top (required)>'
>   /tmp/bundle/ruby/2.6.0/gems/erb_lint-0.0.36/lib/erb_lint/cli.rb:3:in `require'
>   /tmp/bundle/ruby/2.6.0/gems/erb_lint-0.0.36/lib/erb_lint/cli.rb:3:in `<top (required)>'
>   /tmp/bundle/ruby/2.6.0/gems/erb_lint-0.0.36/exe/erblint:6:in `require'
>   /tmp/bundle/ruby/2.6.0/gems/erb_lint-0.0.36/exe/erblint:6:in `<top (required)>'
>   /tmp/bundle/ruby/2.6.0/bin/erblint:23:in `load'
>   /tmp/bundle/ruby/2.6.0/bin/erblint:23:in `<top (required)>'
> ```

Oh boy, I'll check this out soon

**Pull request merged**
