### PR TITLE
Added output formatters (console and JSON)

### PR DESCRIPTION
**Pull request by vzamanillo**
Based on #116 

Linter independent output formatters.

### CODE REVIEW

**Comment by macobo** [comment]
@EiNSTeiN- any interest in getting this merged?

**Comment by vzamanillo** [comment]
> @EiNSTeiN- any interest in getting this merged?
> 
> There's some exciting use-cases for this, from disabling rules file-by-file basis automatically, adding editor support and so on.

I am waiting to finish this, [linter-erb-lint](https://github.com/vzamanillo/linter-erb-lint) if you are interested.

**Comment by vzamanillo** [comment]
> We noticed that this PR either modifies or introduces usage of html_safe, a method which in Rails can cause cross-site scripting (XSS) vulnerabilities. Our team will take a look soon, but for now we recommend reviewing some of the existing materials on XSS at Shopify and alternatives to this method. A good start is the [How Not to html_safe presentation](https://docs.google.com/presentation/d/1uiLXUPtKIIbwcJ__Rx4w2HhKiIYSly7eJI_3PCfANNA/edit?usp=sharing) in the [Security Presentations page](https://vault.shopify.com/Security/Security-Presentations#how-not-to-html_safe).

This PR does not introduce any usage of html_safe, the changes are relative to linting results output formatting, you are free to take a look at the changed files and make a review if you find something wrong.

**Comment by macobo** [comment]
:disappointed:

**Pull request closed without merging**
