### PR TITLE
Drop support for Ruby 2.4

### PR DESCRIPTION
**Pull request by exterm**
it is EOL

### CODE REVIEW

**Comment by exterm** [comment]
The tests on this are broken because erblint is not compatible with current rubocop versions... To be fixed in https://github.com/Shopify/erb-lint/pull/179

**Comment by exterm** [comment]
it was cherry-picked and will be merged with https://github.com/Shopify/erb-lint/pull/179

**Comment by exterm** [comment]
I'm a confused person. This wasn't cherry-picked anywhere and still needs to be merged.

**Comment by thegedge** [comment]
Did you rebase ☝️ 

If not, now that https://github.com/Shopify/erb-lint/pull/179 is merged, I assume we could rebase and get everything 🍏

**Comment by exterm** [comment]
rebasing wasn't the problem; a new release of rubocop incompatible with our style guide was.


I have a good fix though.

**Comment by exterm** [comment]
My good solution doesn't solve the problem :(

**Comment by exterm** [comment]
Problem explanation and attempted fix in https://github.com/Shopify/ruby-style-guide/pull/174.

We can work around the problem for now by restricting rubocop to `< 0.89`.

**Comment by exterm** [comment]
Apparently, we can not - the latest version of rubocop-shopify only supports rubocop `< 0.87`. Have to wait for a rubocop-shopify release.

**Pull request merged**
