### PR TITLE
Add excluded files config option for linters

### PR DESCRIPTION
**Pull request by justinthec**
Adds functionality to exclude a path of files for any linter.

Adds a test and documentation to the README.

For Ruby Review:
@arthurgouveia @volmer

### CODE REVIEW

**Comment by rafaelfranca** [comment]
The  code changes are good but the commits messages not. Could you rebase your branch to squash the commits making them atomic and explaining what each commit does?

**Comment by arthurgouveia** [comment]
🔔 

Also agree with @rafaelfranca. @volmer, any thoughts before merging?

**Comment by volmer** [comment]
Nope, lgtm!

**Comment by arthurgouveia** [comment]
🐑 💨

**Comment by arthurgouveia** [comment]
@justinthec what happened to this

> The code changes are good but the commits messages not. Could you rebase your branch to squash the commits making them atomic and explaining what each commit does?

and this

> 🐑 💨 after squashing into 1 commit.

?

**Comment by justinthec** [comment]
Github has a squashing feature:
image

I only merged 1 commit into master.

**Comment by justinthec** [comment]
I changed the commits to have 4 distinct commits in the PR which explained each part clearly imo:
image

**Comment by justinthec** [comment]
@rafaelfranca 's comment was in reference to the edit commits I made through Github at that point which had commits like:

 - `Update foo.bar.rb`
 - `Update fizz.buzz.rb`
 - `Update foo.bar.rb`
 - `Update foo.bar.rb`

**Comment by arthurgouveia** [comment]
<3

**Pull request merged**
