### PR TITLE
Converts file encoding to UTF-8 and fails on exceptions

### PR DESCRIPTION
**Pull request by cjhutchi**
Take a subset of changes from #135 which should help with handling the encoding errors we were seeing on CI.

### CODE REVIEW

**Comment by exterm** [comment]
Strange, the tests were green locally? 🤔

**Comment by cjhutchi** [comment]
> Strange, the tests were green locally? 🤔

Looks like it's testing against multiple versions. I wonder if that has something to do with it.

**Comment by EiNSTeiN-** [comment]
looks like some test failures may be unrelated

**Comment by exterm** [comment]
Does this gem have a flaky test problem? How can we have unrelated test failures? I just recently merged a PR that had a green build.

Oh wait is master broken now? 🤔

**Comment by cjhutchi** [comment]
> Does this gem have a flaky test problem? How can we have unrelated test failures? I just recently merged a PR that had a green build.
> 
> Oh wait is master broken now? 🤔

So dug into the broken tests, all of them seem related to trying to create temp files of cops for testing inheritance. They run fine locally, but fail on CI, which I presume has to do with creating temp files. I'm going to disable those tests for now to get the build green. And spend some more time digging into TravisCI's docs to figure out how we can work around that.

**Comment by exterm** [comment]
Master was green at some point... I wonder if travis has changed the way they handle `/tmp` ot something like that?

**Pull request merged**
